### ISSUE TITLE
Collection was modified in ConnectionManager

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#267]
Sometimes get this exception. 

```
Reason: Unexpected error :Collection was modified; enumeration operation may not execute.; Code: 50000
   at IO.Ably.Transport.ConnectionManager.<CreateTransport>d__58.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.States.Connection.ConnectionConnectingState.<OnAttachToContext>d__11.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionConnectingState.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass57_0.<<SetState>b__0>d.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 125
Inner exception:
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IO.Ably.Transport.ConnectionAttemptsInfo.GetHost() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionAttemptsInfo.cs:line 164
   at IO.Ably.Transport.ConnectionManager.<CreateTransportParameters>d__77.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 440
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.ConnectionManager.<CreateTransport>d__58.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 167
```

**Comment by withakay** [comment]
I have been unable to repeat this problem, is it still an issue? 
Could. you try v1.1.1, that was released today?

Please reopen if there is still an issue.
