### ISSUE TITLE
NullReferenceException in ConnectionManager.cs

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#72]
Using latest commit. Not happens often. May be relevant, I don't know.
```
 Exception:System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IO.Ably.Transport.ConnectionManager.get_TransportState() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 26
   at IO.Ably.Transport.States.Connection.ConnectionClosingState.OnAttachToContext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionClosingState.cs:line 56
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass52_0.<<SetState>b__0>d.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 114
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at IO.Ably.Transport.ConnectionManager.get_TransportState() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 26
   at IO.Ably.Transport.States.Connection.ConnectionClosingState.OnAttachToContext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionClosingState.cs:line 56
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass52_0.<<SetState>b__0>d.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 114<---
```

**Comment by mattheworiordan** [comment]
Noted @lovetofail, we'll look into it.

**Comment by marto83** [comment]
@lovetofail I see how this could happen from time to time. I'll add a check to make sure a valid state is always returned even if the Transport has been destroyed.

**Comment by lovetofail** [comment]
Got this exception today.
```
==========Items connection: Disconnected, Thread:30 Serial:16
Ably: [Debug] 06:11:45.219 #30 xx Disconnected: Attaching state 
Ably: [Debug] 06:11:45.222 #30 Destroying transport
Ably: [Debug] 06:11:45.225 #30 Closing socket. Current socket is not null
Ably: [Debug] 06:11:45.225 #30 Setting up timer 'Disconnected state timer' to run action after 15 seconds. Autoreset: False
Ably: [Debug] 06:11:45.226 #30 xx Changing state from Disconnected => Connecting. SkipAttach = False.
Ably: [Debug] 06:11:45.227 #30 Aborting timer 'Disconnected state timer'
Ably: [Debug] 06:11:45.228 #30 xx Connecting: BeforeTransition
Ably: [Debug] 06:11:45.229 #30 Connection notifying subscribers for state change `Connecting`
==========Items connection: Connecting, Thread:30 Serial:16
Ably: [Debug] 06:11:45.231 #30 xx Connecting: Attaching state 
Ably: [Debug] 06:11:45.232 #30 Creating transport
Ably: [Info] 06:11:45.234 #30 Sending GET request to http://localhost/ably/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=60&cb=7593
Ably: [Debug] 06:11:45.235 #30 Executing request: http://localhost/ably/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=60&cb=7593
Ably: [Debug] 06:11:45.895 #30 Connecting to web socket on url: wss://us-west-1-a-realtime.ably.io/?accessToken=GFbjCQ.HHrsBjPwYuwPCS04NYdQKyiqvMLk0H2OOJ6rTi4ql43zzw_UHZDbh_Vr8CgwQBhbw6JCUDqmHVS0CFkjdAPv2e0V_NrkqkwbPqC-kbZbhTYDwqkln0mPg7JfieTS_G3SCssKUC_VXtATwvnwCHNVZAUis8zXNAWJca-x8q1TGDjIPQzrQ3wXzUFIn-qn0ANJKY7_Nnr6yffqwYonSl-nSZA&v=0.8&format=msgpack&echo=true&resume=6f8763b9!7WGgdHkukrE5kV-M-14336f8763b9&connection_serial=16
Ably: [Debug] 06:11:45.896 #30 Connecting socket
Ably: [Debug] 06:11:45.897 #30 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 06:11:47.080 #40 Websocket opened!
Ably: [Debug] 06:11:47.081 #30 Transport state changed to: Connected.
Ably: [Debug] 06:11:55.912 #28 Timer 'Connecting state timer' interval 10 seconds elapsed and calling action.
Ably: [Debug] 06:11:55.913 #30 Handling Connecting failure.
Ably: [Debug] 06:11:55.914 #30 xx Changing state from Connecting => Suspended. SkipAttach = False.
Ably: [Debug] 06:11:55.915 #30 Aborting timer 'Connecting state timer'
Ably: [Debug] 06:11:55.915 #30 xx Suspended: BeforeTransition
Ably: [Debug] 06:11:55.916 #30 Connection notifying subscribers for state change `Suspended`
Ably: [Debug] 06:11:55.917 #30 #ubfp:presence: Changing state to: 'Detaching'. Error: Reason: Connection unavailable; Code: 80002
Ably: [Debug] 06:11:55.917 #30 #ubfp:presence: Changing state to: 'Detached'. Error: Reason: Connection unavailable; Code: 80002
Ably: [Debug] 06:11:55.918 #30 Aborting timer '#ubfp:presence timer'
==========Presence channel:Detached ubfp:presence 
==========Presence channel:Detaching ubfp:presence 
Ably: [Debug] 06:11:55.920 #30 #ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=: Changing state to: 'Detaching'. Error: Reason: Connection unavailable; Code: 80002
Ably: [Debug] 06:11:55.920 #30 #ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=: Changing state to: 'Detached'. Error: Reason: Connection unavailable; Code: 80002
Ably: [Debug] 06:11:55.921 #30 Aborting timer '#ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho= timer'
==========Item channel:Detached ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho= 
==========Item channel:Detaching ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho= 
==========Items connection: Suspended, Thread:30 Serial:16
Ably: [Debug] 06:11:55.923 #30 xx Suspended: Attaching state 
Ably: [Debug] 06:11:55.923 #30 Setting up timer 'Suspended state timer' to run action after 30 seconds. Autoreset: False
Ably: [Debug] 06:12:02.023 #40 Websocket message received. Raw: �6f8ba6ba80316397:76�connectionId�3ddzSXRl4r�connectionSerial�timestamp�Exception thrown: 'System.NullReferenceException' in IO.Ably.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Ably: [Debug] 06:12:02.553 #23 Websocket message received. Raw: 648�	��actionException thrown: 'System.NullReferenceException' in IO.Ably.dll
Ably: [Debug] 06:12:02.580 #23 Websocket data message received. Raw: 105
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Ably: [Debug] 06:12:02.581 #23 Websocket data message received. Raw: { "action" : 15, "id" : "3ddzSXRl4r-27032", "count" : 38, "channel" : "ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=", "channelSerial" : "6f8ba6ba80316397:81", "connectionId" : "3ddzSXRl4r", "connectionSerial" : 26, "timestamp" : 1467310318161, "messages" : [ { "name" : "iphone", "clientId" : "Seer", "encoding" : "utf-8\/cipher+aes-128-cbc", "data" : "0xB6B22120F5D561A7EB6CDB61D3CD81AD07EDCB48CC73B628A3CDA0009CE4A96B" } ] }
Ably: [Debug] 06:12:02.595 #23 Websocket data message received. Raw: { "action" : 15, "id" : "3ddzSXRl4r-27034", "count" : 37, "channel" : "ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=", "channelSerial" : "6f8ba6ba80316397:82", "connectionId" : "3ddzSXRl4r", "connectionSerial" : 27, "timestamp" : 1467310318162, "messages" : [ { "name" : "16204", "clientId" : "Seer", "encoding" : "utf-8\/cipher+aes-128-cbc", "data" : "0xBCF6AF847EA0A72A71EA33B42636C8C4400851319A594E0DAA2D1D74194F70E7" } ] }
==========Received: 302001136043
Ably: [Debug] 06:12:02.617 #23 Websocket data message received. Raw: { "action" : 15, "id" : "3ddzSXRl4r-27037", "count" : 38, "channel" : "ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=", "channelSerial" : "6f8ba6ba80316397:83", "connectionId" : "3ddzSXRl4r", "connectionSerial" : 28, "timestamp" : 1467310318164, "messages" : [ { "name" : "iphone", "clientId" : "Seer", "encoding" : "utf-8\/cipher+aes-128-cbc", "data" : "0xF33C847DCD36101179EAA5412E4D97318623AA19A0250E6B04ACC76B4E18449B" } ] }
Ably: [Debug] 06:12:02.639 #38 Websocket data message received. Raw: { "action" : 15, "id" : "3ddzSXRl4r-27038", "count" : 38, "channel" : "ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=", "channelSerial" : "6f8ba6ba80316397:84", "connectionId" : "3ddzSXRl4r", "connectionSerial" : 29, "timestamp" : 1467310318179, "messages" : [ { "name" : "iphone", "clientId" : "Seer", "encoding" : "utf-8\/cipher+aes-128-cbc", "data" : "0xEDA054ABA34AB50056547EEC2244D6FBD3986EEE4590E1F80DC10349091437F0" } ] }
==========Received: 122031769364
Ably: [Debug] 06:12:02.660 #38 Websocket data message received. Raw: { "action" : 15, "id" : "3ddzSXRl4r-27041", "count" : 38, "channel" : "ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=", "channelSerial" : "6f8ba6ba80316397:85", "connectionId" : "3ddzSXRl4r", "connectionSerial" : 30, "timestamp" : 1467310318180, "messages" : [ { "name" : "iphone", "clientId" : "Seer", "encoding" : "utf-8\/cipher+aes-128-cbc", "data" : "0xC61578C634585C60B01401806F38404B5F1486A949F4B0830E26B2EE42313110" } ] }
==========Received: 272292121026
==========Received: 272292121035
==========Received: 222171831204
LE: Adding Line: Thu Jun 30 21:12:03.0815 +03:00 2016 Logger : Error, 2.0.0.73, nKWyBjoFxgd0lswgs+LWfVvR1Ho=;aaaa-1D94-5823-458F-96DB-CED1-B99F_Enterprise Exception:System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IO.Ably.Transport.AcknowledgementProcessor.OnMessageReceived(ProtocolMessage message) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\AcknowledgementProcessor.cs:line 51
   at IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 436
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 412
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at IO.Ably.Transport.AcknowledgementProcessor.OnMessageReceived(ProtocolMessage message) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\AcknowledgementProcessor.cs:line 51
   at IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 436
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 412<---

LE
```

**Comment by marto83** [comment]
The library received a message it couldn't deserialise but continued to try and process it. That's where it failed. I'll add a check to ignore data that does not deserialise as a Message. 

Thanks for pointing this out. I'll just double check with @mattheworiordan what the desired behaviour should be and I'll push a fix by the end of the day.

**Comment by mattheworiordan** [comment]
@marto83 I believe http://docs.ably.io/client-lib-development-guide/features/#RSL6b covers that scenario.  The message must be delivered, but in an encoded format with the encoding attribute populated, and an error should be emitted on the channel
