### ISSUE TITLE
authUrl authentication fails

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#74]
@marto83 please see the log below for a customer using the `ClientOptions` `authUrl` option:

```
Native library pre-loader is trying to load native SQLite library "F:\Users\bs\Documents\Visual Studio 2015\Projects\UCryptLight\src\UCryptLight\UCryptLight\bin\Debug\x64\SQLite.Interop.dll"...
Ably: [Debug] 08:33:37.599 #8 Protocol set to: MsgPack
Ably: [Debug] 08:33:37.602 #8 Initializing message encodings. json,utf-8,cipher,base64 initialized
Ably: [Info] 08:33:37.606 #8 Using token authentication.
Ably: [Info] 08:33:37.608 #8 Authentication method: Token auth with URL
Ably: [Debug] 08:33:37.647 #33 ConnectionManager thread created
Ably: [Debug] 08:33:37.650 #8 xx Changing state from Initialized => Connecting. SkipAttach = False.
Ably: [Debug] 08:33:37.654 #33 xx Connecting: BeforeTransition
Ably: [Debug] 08:33:37.656 #33 Connection notifying subscribers for state change `Connecting`
Ably: [Debug] 08:33:37.658 #33 xx Connecting: Attaching state 
Ably: [Debug] 08:33:37.660 #33 Creating transport
Ably: [Info] 08:33:37.689 #33 Sending POST request to http://api-beta.foo.com/rtc/auth/
Ably: [Debug] 08:33:37.694 #33 Executing request: http://api-beta.foo.com/rtc/auth/
Ably: [Debug] 08:33:39.713 #8 #private-a012a914cce6096c4a02a29da51dbc58: Changing state to: 'Attaching'. 
Ably: [Debug] 08:33:39.715 #8 Aborting timer '#private-a012a914cce6096c4a02a29da51dbc58 timer'
Ably: [Debug] 08:33:39.715 #8 Setting up timer '#private-a012a914cce6096c4a02a29da51dbc58 timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 08:33:39.718 #8 Current state: Connecting. Sending message: { action=Attach }
Ably: [Debug] 08:33:39.721 #8 Queuing message with action: Attach. Connection State: Connecting
Ably: [Info] 08:33:43.029 #33 Sending POST request to /keys//requestToken
Ably: [Debug] 08:33:43.133 #8 #private-cc-099ba954299c4fddbc035fb40d9175b0: Changing state to: 'Attaching'. 
Ably: [Debug] 08:33:43.133 #8 Aborting timer '#private-cc-099ba954299c4fddbc035fb40d9175b0 timer'
Ably: [Debug] 08:33:43.133 #8 Setting up timer '#private-cc-099ba954299c4fddbc035fb40d9175b0 timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 08:33:43.133 #8 Current state: Connecting. Sending message: { action=Attach }
Ably: [Debug] 08:33:43.133 #8 Queuing message with action: Attach. Connection State: Connecting
Ably: [Debug] 08:33:43.158 #8 #private-cc-f368132e7f23403aa977b1abd207ec43: Changing state to: 'Attaching'. 
Ably: [Debug] 08:33:43.158 #8 Aborting timer '#private-cc-f368132e7f23403aa977b1abd207ec43 timer'
Ably: [Debug] 08:33:43.158 #8 Setting up timer '#private-cc-f368132e7f23403aa977b1abd207ec43 timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 08:33:43.158 #8 Current state: Connecting. Sending message: { action=Attach }
Ably: [Debug] 08:33:43.158 #8 Queuing message with action: Attach. Connection State: Connecting
Ably: [Debug] 08:33:43.666 #33 Executing request: /keys//requestToken
Ably: [Debug] 08:33:44.398 #33 Aborting timer 'Connecting state timer'
Ably: [Error] 08:33:44.403 #33 Error attaching to context Error code: 40400
Status code: NotFound
Reason: Could not find path: /keys/requestToken
Reason: Could not find path: /keys/requestToken; Code: 40400; HttpStatusCode: (404)NotFound
   at IO.Ably.AblyHttpClient.<Execute>d__13.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Http\AblyHttpClient.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyRest.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyRest.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.AblyRest.<ExecuteRequest>d__32`1.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyRest.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.AblyAuth.<RequestTokenAsync>d__40.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyAuth.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.AblyAuth.<AuthoriseAsync>d__44.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyAuth.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.AblyAuth.<GetCurrentValidTokenAndRenewIfNecessaryAsync>d__39.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\AblyAuth.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.TransportParams.<Create>d__49.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Transport\TransportParams.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.ConnectionManager.<CreateTransportParameters>d__72.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 396
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.ConnectionManager.<CreateTransport>d__53.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.States.Connection.ConnectionConnectingState.<OnAttachToContext>d__11.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Transport\States\Connection\ConnectionConnectingState.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass52_0.<<SetState>b__0>d.MoveNext() in F:\Users\bs\Desktop\ably-dotnet-update-to-match-idl\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 113

Ably: [Debug] 08:33:44.403 #33 xx Changing state from Connecting => Failed. SkipAttach = False.
Ably: [Debug] 08:33:44.403 #33 Aborting timer 'Connecting state timer'
Ably: [Debug] 08:33:44.403 #33 xx Failed: BeforeTransition
Ably: [Debug] 08:33:44.404 #33 Destroying transport
Ably: [Debug] 08:33:44.404 #33 Connection notifying subscribers for state change `Failed`
Ably: [Debug] 08:33:44.405 #33 #private-a012a914cce6096c4a02a29da51dbc58: Changing state to: 'Failed'. Error: Reason: Could not find path: /keys/requestToken; Code: 40400; HttpStatusCode: (404)NotFound
Ably: [Debug] 08:33:44.406 #33 #private-cc-099ba954299c4fddbc035fb40d9175b0: Changing state to: 'Failed'. Error: Reason: Could not find path: /keys/requestToken; Code: 40400; HttpStatusCode: (404)NotFound
Ably: [Debug] 08:33:44.407 #33 #private-cc-f368132e7f23403aa977b1abd207ec43: Changing state to: 'Failed'. Error: Reason: Could not find path: /keys/requestToken; Code: 40400; HttpStatusCode: (404)NotFound
Ably: [Debug] 08:33:44.407 #33 xx Failed: Attaching state 
Ably Connection Error: NotFound : Could not find path: /keys/requestToken
```
 
@marto83  can you please advise what the issue is?

**Comment by marto83** [comment]
This seems odd. Do you have details about what exact settings were used. I have an idea and will try and replicate it shortly.

**Comment by mattheworiordan** [comment]
No, but I can email the customer directly if you have a specific question?

**Comment by tulpn** [comment]
The log was generated by using the following code:

```
System.Collections.Generic.Dictionary<string, string> AH = new System.Collections.Generic.Dictionary<string, string>();
            AH.Add("Authorization", "Token " + Common.GetHTTPFileAuthToken());
            AH.Add("X-DEVICEID", FingerPrint.Value());
new AblyRealtime(new ClientOptions
            {
                AuthUrl = new System.Uri("http://api-beta.foo.com/rtc/auth/"),
                AuthMethod = HttpMethod.Post,
                AuthHeaders = AH,
                Key = "..."
            });
```
After further investigation I recognised that the return value from the URL was not correctly formatted. I changed it to (python):

```
...
token = p.generate_auth_token(request.user.str_uuid, capability)        
return Response(token.to_dict())
```

Seem to have resolved the issue.

**Comment by marto83** [comment]
Thank @tulpn. What TTL do you use? The current token expiry time is set to 3600 ms after it was created. 
based on this line: `Ably: [Debug] 08:45:24.535 #33 Response: { "token" : "....1ZvUvdWAUfu_ophFwzYPOb5PpyleFQ7gwqb3jlNcwHXCTFC74", "keyName" : "....", "issued" : 1467189926092, "expires" : 1467189929692, "capability" : "{\"*\":[\"*\"]}", "clientId" : "a012a914-cce6-096c-4a02-a29da51dbc58" }`

**Comment by tulpn** [comment]
Well, makes sense. Copy & Paste error. I took a TTL of 3600 by copying the code of "Generate a TokenRequest"  https://github.com/ably/ably-python

**Comment by marto83** [comment]
Great. Let me know if you have any other issues. I'll going to add some validation of the json returned from the AuthUrl so you can get a better error message. 

Are you happy for me to close this issue?

**Comment by tulpn** [comment]
Yes. Thank you for your help.
