### ISSUE TITLE
Unity: When building for iOS, an IL2CPP error prevents the app working

### ISSUE THREAD

**Issue by eAi** [ably/ably-dotnet#751]
Is anyone aware of this issue on Unity 2020.3.14 that occurs when building for iOS with IL2CPP? This didn't occur before the integration of the Ably package and may mean we need to use a different solution.

    Exception: IL2CPP error for method 'System.Threading.Channels.Channel`1<T> System.Threading.Channels.Channel::CreateUnbounded(System.Threading.Channels.UnboundedChannelOptions)' in assembly '/Users/test/buildAgent/work/99ab41247e8a53b7_iOS/Temp/StagingArea/Data/Managed/System.Threading.Channels.dll'
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Mono.Cecil.GenericInstanceType..ctor(TypeReference type)
       at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 71
       at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
       at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, TypeReference typeReference) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 11
       at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 73
       at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
       at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 116
       at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
       at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
       at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
       at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
       at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
       at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
       at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
       at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 119
    <snipped>

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1140) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
Thank you for raising this. Does the above happen purely by including the Ably package or does occur after creating Ably types? Do you have any sample code / a gist that surfaces this error please?

**Comment by eAi** [comment]
Unfortunately I can't reproduce this in an empty project with just Ably include (though that did reveal some other issues that I've since reported).

Even with some basic code that uses Ably included (to make sure it isn't stripped) this error doesn't occur. I'll try to dig deeper.

The real project this is being used in is large - and the size may be part of what is tripping up IL2CPP. The build error occurs on more than one machine.

**Comment by eAi** [comment]
I've managed to reproduce this in a small project and find a temporary workaround after a whole day of work on this. 

The underlying issue is that Unity's 'managed stripping' is stripping too much when set to "high" which causes IL2CPP to fail (perhaps because it can't find a type that it actually needs). A workaround is to set managed stripping to "medium" but that does increase the build size somewhat so isn't ideal. There may be some way that Ably could work around this (perhaps explicitly using whatever type is being stripped somewhere) but it isn't obvious what type is missing. 

I've reported a bug to Unity (1358995 on their internal issue tracker) which hopefully they'll get around to fixing at some point.

**Comment by marto83** [comment]
@eAi do you mind sharing the project where you can reproduce it. I can try to explicitly use some of the classes used in the Factory method and see what fixes it. 

Can you manually exclude types so they are not stripped?

The error happens when trying to initialize an `UnboundedChannel` and here is the source for it: https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Threading/Channels/Channel.cs#L19

**Comment by eAi** [comment]
@marto83 Here we go. I'm using the latest Unity 2020 version (2020.3.16).

[Ably Bug Repro.zip](https://github.com/ably/ably-dotnet/files/7006667/Ably.Bug.Repro.zip)

This project has a link.xml file in it in an attempt to prevent stripping from breaking things - this doesn't work - which is odd.

I'm able to reproduce the issue by taking some of the stripped DLLs that Unity produces before it runs them through IL2CPP and manually running IL2CPP on it. When I do the same with managed stripping set to Medium, it works. When I use link.xml with managed stripping set to high, the DLLs produced are much larger (as you'd expect) but still don't work. Which is odd... Attached below are the DLLs pre-IL2CPP (and post-stripping) with different stripping levels. There's a readme in this zip file that has the command line to run to reproduce (or not) the issue with these.

[Stripped Assemblies pre IL2CPP.zip](https://github.com/ably/ably-dotnet/files/7007301/Stripped.Assemblies.pre.IL2CPP.zip)

**Comment by marto83** [comment]
@eAi Thanks for the code base. Just to manage expectations, I'm off next week and will have a look at it when I come back the week after.

**Comment by eAi** [comment]
Unity has accepted this as a bug: https://issuetracker.unity3d.com/issues/il2cpp-build-fails-when-managed-stripping-level-is-set-to-high

**Comment by QuintinWillison** [comment]
It looks like [the accepted Unity bug](https://github.com/ably/ably-dotnet/issues/751#issuecomment-910286344) has been fixed. This issue has not had any further activity for over a year, so I'm assuming it's no longer relevant.
