### ISSUE TITLE
Skipped Test: PresenceSandboxSpecs.Presence_ShouldHaveInternalMapForCurrentConnectionId

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#838]
Re-enable the `PresenceSandboxSpecs.Presence_ShouldHaveInternalMapForCurrentConnectionId` test.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1190) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Sometimes I am seeing a timeout error for the test, I will try to reproduce it multiple times.

**Comment by sacOO7** [comment]
Sometimes showing error 

```
        IO.Ably.Tests.Realtime.PresenceSandboxSpecs+GeneralPresenceSandBoxSpecs.Presence_ShouldHaveInternalMapForCurrentConnectionId(protocol: Json) [FAIL]
      Expected the enum to be PresenceAction.Leave {value: 3}, but found PresenceAction.Present {value: 1}.
      Stack Trace:
        /_/Src/FluentAssertions/Execution/XUnit2TestFramework.cs(33,0): at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
        /_/Src/FluentAssertions/Execution/AssertionScope.cs(273,0): at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
        /_/Src/FluentAssertions/Primitives/EnumAssertions.cs(61,0): at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
        src\IO.Ably.Tests.Shared\Realtime\PresenceSandboxSpecs.cs(563,0): at IO.Ably.Tests.Realtime.PresenceSandboxSpecs.GeneralPresenceSandBoxSpecs.<Presence_ShouldHaveInternalMapForCurrentConnectionId>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
