### ISSUE TITLE
Skipped Test: PresenceSandboxSpecs.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#843]
Re-enable the `PresenceSandboxSpecs.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC` test.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1200) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Failing with error 
```
[xUnit.net 00:00:03.23]     IO.Ably.Tests.Realtime.PresenceSandboxSpecs+GeneralPresenceSandBoxSpecs+ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(protocol: Json) [FAIL]
  X IO.Ably.Tests.Realtime.PresenceSandboxSpecs+GeneralPresenceSandBoxSpecs+ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(protocol: Json) [1s 958ms]
  Error Message:
   Expected presence2.SyncComplete to be true, but found False.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at IO.Ably.Tests.Realtime.PresenceSandboxSpecs.GeneralPresenceSandBoxSpecs.ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(Protocol protocol) in D:\a\ably-dotnet\ably-dotnet\src\IO.Ably.Tests.Shared\Realtime\PresenceSandboxSpecs.cs:line 1516
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 Test end disposing connections: 2
```

**Comment by sacOO7** [comment]
Also fails with error 
```
[xUnit.net 00:00:02.78]     IO.Ably.Tests.Realtime.PresenceSandboxSpecs+GeneralPresenceSandBoxSpecs+ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(protocol: Json) [FAIL]
  X IO.Ably.Tests.Realtime.PresenceSandboxSpecs+GeneralPresenceSandBoxSpecs+ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(protocol: Json) [1s 814ms]
  Error Message:
   Expected boolean to be true, but found False.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at IO.Ably.Tests.Realtime.PresenceSandboxSpecs.GeneralPresenceSandBoxSpecs.ChannelStateChangeSideEffects.WhenChannelBecomesAttached_ShouldSendQueuedMessagesAndInitiateSYNC(Protocol protocol) in D:\a\ably-dotnet\ably-dotnet\src\IO.Ably.Tests.Shared\Realtime\PresenceSandboxSpecs.cs:line 1532
--- End of stack trace from previous location where exception was thrown ---1
```
