### ISSUE TITLE
Skipped Test: ChannelSandboxSpecs.IdempotentPublishing_SimulateErrorAndRetry

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#847]
Re-enable the `ChannelSandboxSpecs.IdempotentPublishing_SimulateErrorAndRetry` test.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1203) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Sometimes fails with error 
``` 
IO.Ably.Tests.Rest.ChannelSandboxSpecs.IdempotentPublishing_SimulateErrorAndRetry(protocol: Json) [1 s]
  Error Message:
   Expected collection {Id: 152939b0-45a2-4a4d-808d-d45b339b7b51, Name: test1, Data: test1, Encoding: , Timestamp: 2/1/2022 5:18:36 PM +00:00, Id: XI5f6zWDZVru:0, Name: test, Data: test, Encoding: , Timestamp: 2/1/2022 5:18:36 PM +00:00, Id: eUUxAjWKYq:0:0, Name: test, Data: test data, Encoding: , Timestamp: 2/1/2022 5:17:34 PM +00:00, Id: xs4y7-7PrV:1:0, Name: test, Data: best, Encoding: , Timestamp: 2/1/2022 5:17:09 PM +00:00, Id: xs4y7-7PrV:0:0, Name: test, Data: best, Encoding: , Timestamp: 2/1/2022 5:17:09 PM +00:00, Id: fdpPL_vCUv:0:0, Name: event, Data: data, Encoding: , Timestamp: 2/1/2022 5:16:46 PM +00:00} to contain 1 item(s), but found 6.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Collections.GenericCollectionAssertions`3.HaveCount(Int32 expected, String because, Object[] becauseArgs)
   at IO.Ably.Tests.Rest.ChannelSandboxSpecs.IdempotentPublishing_SimulateErrorAndRetry(Protocol protocol) in /Users/runner/work/ably-dotnet/ably-dotnet/src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 Message: {"id":"152939b0-45a2-4a4d-808d-d45b339b7b51","name":"test1","timestamp":1643735916480,"data":"test1"}
 Message: {"id":"XI5f6zWDZVru:0","clientId":"111","name":"test","timestamp":1643735916423,"data":"test"}
 Message: {"id":"eUUxAjWKYq:0:0","connectionId":"eUUxAjWKYq","name":"test","timestamp":1643735854531,"data":"test data"}
 Message: {"id":"xs4y7-7PrV:1:0","connectionId":"xs4y7-7PrV","name":"test","timestamp":1643735829481,"data":"best"}
 Message: {"id":"xs4y7-7PrV:0:0","connectionId":"xs4y7-7PrV","name":"test","timestamp":1643735829453,"data":"best"}
 Message: {"id":"fdpPL_vCUv:0:0","connectionId":"fdpPL_vCUv","name":"event","timestamp":1643735806799,"data":"data"}
```
