### ISSUE TITLE
Various null reference exceptions

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#85]
Hi I'm using this revision 330f536d28ae703701b2dc565f12a3ce561cce75
A few kind of exceptions pop up from time. Maybe you can spot some issues. 

Also, should I close myself issues that I've opened in the past?

[_Exceptions.txt](https://github.com/ably/ably-dotnet/files/513471/_Exceptions.txt)
'''
Exception:System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at WebSocket4Net.WebSocket.ClearTimer()
   at WebSocket4Net.WebSocket.Close(Int32 statusCode, String reason)
   at WebSocket4Net.WebSocket.Close(String reason)
   at WebSocket4Net.WebSocket.Close()
   at IO.Ably.Realtime.WebSocketTransport.Close(Boolean suppressClosedEvent) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Realtime\WebSocketTransport.cs:line 79
   at IO.Ably.Transport.ConnectionManager.DestroyTransport(Boolean suppressClosedEvent) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 166
   at IO.Ably.Transport.States.Connection.ConnectionDisconnectedState.OnAttachToContext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionDisconnectedState.cs:line 52
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass50_0.<<SetState>b__0>d.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<RetryBecauseOfTokenError>d__56.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.States.Connection.ConnectionConnectedState.<OnMessageReceived>d__8.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionConnectedState.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 435
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 412
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at WebSocket4Net.WebSocket.ClearTimer()
   at WebSocket4Net.WebSocket.Close(Int32 statusCode, String reason)
   at WebSocket4Net.WebSocket.Close(String reason)
   at WebSocket4Net.WebSocket.Close()
   at IO.Ably.Realtime.WebSocketTransport.Close(Boolean suppressClosedEvent) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Realtime\WebSocketTransport.cs:line 79
   at IO.Ably.Transport.ConnectionManager.DestroyTransport(Boolean suppressClosedEvent) in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 166
   at IO.Ably.Transport.States.Connection.ConnectionDisconnectedState.OnAttachToContext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionDisconnectedState.cs:line 52
   at IO.Ably.Transport.ConnectionManager.<>c__DisplayClass50_0.<<SetState>b__0>d.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<RetryBecauseOfTokenError>d__56.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.States.Connection.ConnectionConnectedState.<OnMessageReceived>d__8.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\States\Connection\ConnectionConnectedState.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 435
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext() in C:\Temp\Push\ably2\ably-dotnet\src\IO.Ably.Shared\Transport\ConnectionManager.cs:line 412
'''

**Comment by mattheworiordan** [comment]
Thanks @lovetofail for notifying us.  We'll get back to you soon on this.

**Comment by marto83** [comment]
Hi lovetofail. 

I had a look and this happens if we call in quick succession DestroyTransport. I suspect one happens when a message was received while the transport was being disposed. 

I haven't managed to reproduce it. I'll add a guard clause around destroy transport and will add a lock to make sure we can't call destroy transport twice. 

P.S. I'll go through the old tickets now and close them. Thanks

**Comment by mattheworiordan** [comment]
@marto83 any update on this?
